application: speakcode
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /public
  static_dir: public

- url: /
  script: controllers.main.app

- url: /contact
  script: controllers.contact.app
  
- url: /contact_thank_you
  script: controllers.contact_thank_you.app
  
- url: /best_friends
  script: controllers.best_friends.app
  
  
libraries:
- name: webapp2
  version: "2.5.1"
